### ISSUE TITLE
Into Mailchimp: Monthly

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/email-templates#25]
- [x] Create any additional assets needed for future mailings
- [x] Review template with Evan to confirm template meets requirements
- [x] Upload template into Mailchimp

**Due:** Talk to Evan to determine deadline

**Comment by heyitsolivia** [comment]
Monthly template is loaded into Mailchimp with Mailchimp template tags, but isn't ready to be merged into master yet. There's an issue with Mailchimp's automatic css inliner that I want to resolve before doing so— see #37
